spring:
  application:
    name: order-consumer
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: order-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        "[schema.registry.url]": ${SCHEMA_REGISTRY_URL:http://localhost:8081}
        "[specific.avro.reader]": true
    listener:
      ack-mode: record
      concurrency: 3
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        "[schema.registry.url]": ${SCHEMA_REGISTRY_URL:http://localhost:8081}
        "[auto.register.schemas]": true
        "[specific.avro.reader]": true
    admin:
      fail-fast: true
      properties:
        "[bootstrap.servers]": ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
server:
  port: ${SERVER_PORT:8081}
order:
  topic: ${ORDER_TOPIC:orders.v1}
  dlq-topic: ${ORDER_DLQ_TOPIC:orders.v1.dlq}
logging:
  level:
    "[org.springframework.kafka]": INFO
    "[com.example.consumer]": INFO
